spring:
  profiles:
    active: dev
  messages:
    basename: i18n/message
    encoding: UTF-8    
logging:
  level:
    org:
      springframework:
        web: DEBUG
    com:
      example: DEBUG
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"
mybatis:
  mapper-locations: classpath:/sql/sample/*.xml
  configuration.map-underscore-to-camel-case: true
  type-aliases-package: com.example.vo
server:
  port: ${PORT:5000}

---
  
spring:
  profiles: dev  
  datasource:
    url: jdbc:postgresql://10.211.55.10:5432/postgres
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

---

spring:
  profiles: prd  
  datasource:
    url: ${JDBC_DATABASE_URL:}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10